name: imgroi_env

channels:
  - conda-forge

dependencies:
  # General dependencies
  - pip==9.0.1
  - wheel==0.29.0
  - coverage==3.7.1
  - python-coveralls==2.5.0

  # Requirements
  - numpy==1.11.3
  - mahotas==1.4.3
